when:
  event:
    - push
  branch:
    - master
    - main
    - fix/slskd-download-response-parsing

steps:
  - name: build
    image: rust:1.91-bookworm
    commands:
      - apt-get update && apt-get install -y pkg-config libssl-dev nodejs npm
      - cargo install dioxus-cli
      - npm install
      - npx @tailwindcss/cli -i ./web/assets/input.css -o ./web/assets/tailwind.css
      - dx bundle --package web --release

  - name: docker
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: localhost:30500
      repo: soulbeet
      tags: ${CI_COMMIT_SHA:0:8}
      dockerfile: Dockerfile
      insecure: true
      skip_tls_verify: true
