when:
  event:
    - push
  branch:
    - master
    - main
    - fix/slskd-download-response-parsing

steps:
  - name: build
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: localhost:30500
      repo: soulbeet
      tags: ${CI_COMMIT_SHA:0:8}
      dockerfile: Dockerfile
      insecure: true
      skip_tls_verify: true
